### ISSUE TITLE
1.19 ?

### ISSUE THREAD

**Issue by maplepy** [Zgoly/Meteorist#1]
Will you update the addon or is it not something planned?

**Comment by Zgoly** [comment]
> Will you update the addon or is it not something planned?

@maplepy I have small problems and I need to fix them. I think I will update it in 12 hours.

**Comment by Zgoly** [comment]
@maplepy I managed to update faster than I thought lol
Get it [here](https://github.com/zgoly/meteorist/releases/latest)

**Comment by maplepy** [comment]
Nice! Thank you very much buddy
