### ISSUE TITLE
[Suggestion] Cristal selfkill, baritone Farmer/killer, 2d Hitbox 

### ISSUE THREAD

**Issue by Maltus32** [Zgoly/Meteorist#11]
### Description

I saw a module in a diffrent client that gave other players hacks and i was wondering if it was possible to let them place cristals on them self or hit them self and could you controlle other players with baritone (killing or farming). A 2d Hitbox with a healthbar would also be cool.

### Before submitting a suggestion

- [x] This feature doesn't already exist.

- [x] This wasn't already suggested.

**Comment by Zgoly** [comment]
I have a question: why want to have ability to self crystal or hit yourself?
Meteor has built-in `.damage` command.

What about 2D Hitbox and health bar:
 You can do `2D Hitbox` with module `ESP` with mode `2D`
You can do `Health bar` with module `Nametags`

**Comment by MJMALTE32** [comment]
The self crystal or hit wouldn´t make me hit myself, but someone else hit himself so it bypasses antireach

**Comment by Zgoly** [comment]
I don't think I will add this. Better to suggest these features in meteor repo.
