### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JeFt1g** [Zgoly/Meteorist#12]
### Describe the bug

don't work zKillAura 

### Steps to reproduce

```bash
idk
```

### Meteorist Version

1.4v

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
I don't have the knowledge to complete this module yet.

zKillaura should **already work**, just to work you need:
1) Add entity in target list
2) Look at entity
3) Hold space

After I know how to set the player's look yaw and pitch to entity, I will **finish it**.
