### ISSUE TITLE
[Suggestion] auto leave with time

### ISSUE THREAD

**Issue by playeur242** [Zgoly/Meteorist#14]
### Description

well basicly it would automaticly leave after a certain time like 1h or minutes and stuff

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
I think this function will be useless for several reasons:
**1.** Windows provides ability to create a scheduled tasks
**2.** You can do it with other programs like `AutoHotkey`

Keep in mind that you can't just say _"Minecraft, please leave from server after 1 hour"_
Ticks used for this. If connection between client and server will be bad, then tick, which is usually 50 milliseconds, can change. And your `1 hour` can turn into something like `1 hour, 6 minutes, and 25 seconds`.

**Comment by playeur242** [comment]
I mean its not really an issue if its more than 1h its just useful when you have farms and you know more or less when you'll have enough material using the farm.

**Comment by Zgoly** [comment]
Now you can use `Instructions` module for it!
Basically, you can do something like:
1. Add Delay (time you need to wait in ticks, for hour it's 20 * 60 * 60 = `72000`)
2. Add command `.disconnect`
3. (Optional) Add command `.toggle instructions` (to disable module)

Hope this helps!
