### ISSUE TITLE
[Suggestion] Support 1.19.3 plz

### ISSUE THREAD

**Issue by IF-desu** [Zgoly/Meteorist#16]
### Description

Meteorist is one of the best addons of meteor client I think,but it just support 1.19.2-
1.19.3When?

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
Hi! Thanks for using Meteorist!

I ran version made for Minecraft 1.19.2 on 1.19.3 and everything worked great.

If you got a problem / bug / crash, then create a new issue or write here everything you got.

If your problem / bug / crash is related to new version, I will update Meteorist.

**Comment by IF-desu** [comment]
OK,thanks
