### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Tripinpix** [Zgoly/Meteorist#17]
### Describe the bug

Auto feed and Auto heal crashes the game

### Steps to reproduce

```bash
Enabled auto feed or auto heal crashed the game once auto feed reaches the set hunger level. Same applies to auto heal but for health. I have the command set for /feed and /heal for the respective module.
```

### Meteorist Version

v0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
I think this may be due to the fact that Meteorist is still for Minecraft 1.19.2, although it supports 1.19.3. I'll take a look and if it's true then I'll update it to 1.19.3 and close this issue.

**Comment by Zgoly** [comment]
Fixed!
Get it [here](https://github.com/zgoly/meteorist/releases/latest)
