### ISSUE TITLE
Update 1.18.2

### ISSUE THREAD

**Issue by Vlad-ang** [Zgoly/Meteorist#2]
### Description

Add to 1.18.2 new modules and gui elements from last 1.19 updates

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [x] This wasn't already suggested.

**Comment by Zgoly** [comment]
Unfortunately I **can't do it** for several reasons:
- I don't have a `GO BACK TO MINECRAFT 1.18.2` button, so if I need to update Meteorist 1.18.2 to last release, I will have to roll back a lot of changes that happened in fabric & meteor from 1.18 to 1.19
- Meteor only for new versions of Minecraft, and Meteorist is directly related to it

If you need to play on 1.18.2 Minecraft server, download [ViaFabric](https://www.curseforge.com/minecraft/mc-mods/viafabric).
If you're worried about the recently released & hated report system, then download [No Chat Reports](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports).
If you have any other reason to use 1.18.2 version, you can download Meteorist source code, edit it for 1.18.2, and compile it. Use [IntelliJ IDEA Community Edition](https://www.jetbrains.com/idea/download) for this.
