### ISSUE TITLE
Message Delay

### ISSUE THREAD

**Issue by deterlua** [Zgoly/Meteorist#23]
### Description

Pretty simple explanation, message delay. delays your message in macros for however long you like.

I find it useful for myself because I'm experimenting and I kind of need it.

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
Yes, I like this idea. I will try to add this ability later, but I'm not sure if I can. _(I don't know why this hasn't been implemented in Meteor yet.)_

**Comment by deterlua** [comment]
I just want this so I can teleport through walls without getting lagged back because I go too fast.

**Comment by deterlua** [comment]
For example if you make a macro "toggle flight" and then "input up 5" with another "toggle flight" after that it only toggles the flight without going upwards.

**Comment by Zgoly** [comment]
I created a pull request [here](https://github.com/MeteorDevelopment/meteor-client/pull/3739). If it will be rejected, I will add it to Meteorist.

**Comment by deterlua** [comment]
yo sorry to brag but is it possible to add delay between certain/different messages?

**Comment by deterlua** [comment]
hello?

**Comment by Zgoly** [comment]
For now you can use `Instructions` module.

**Comment by deterlua** [comment]
dang you responded after 10 years
