### ISSUE TITLE
[Bug] Game Crashes when using Dm Spam

### ISSUE THREAD

**Issue by QuickMash** [Zgoly/Meteorist#25]
### Describe the bug

Game Crashes when clicked on Dm Spam

### Steps to reproduce

```bash
Click on Dm Spam
```

### Meteorist Version

1.20

### Minecraft Version

1.20.1

### Operating System

Windows 10

### Before submitting a bug report

- [x] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by QuickMash** [comment]
BTW I was in an empty server

**Comment by Zgoly** [comment]
Have you changed settings in `DmSpam`? If so, which ones?

**Comment by Zgoly** [comment]
Try now with [new update](https://github.com/Zgoly/Meteorist/releases/tag/v1.6). Should work now.

**Comment by masongama** [comment]
it still does not work

**Comment by Zgoly** [comment]
@Fiz-Victor can you attach your Minecraft logs? I need to know more details.

**Comment by Fiz-Victor** [comment]
DM Spam is broken after 1.6, but in 1.5 the game does not crash

**Comment by Fiz-Victor** [comment]
The game did not crash but dm is just broken.

**Comment by Zgoly** [comment]
Try to reset all module settings.

**Comment by Zgoly** [comment]
I think now it's fixed! If it's not, write more details and I will re-open it, or just create new issue.
