### ISSUE TITLE
[Bug] Fast-Bridge

### ISSUE THREAD

**Issue by RuriYoshinova** [Zgoly/Meteorist#26]
### Describe the bug

Doesn't work anymore

### Steps to reproduce

```bash
- Turn it on
- Go to the edge of any platforms
```

### Meteorist Version

v1.5

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
[Fixed!](https://github.com/Zgoly/Meteorist/releases/tag/v1.6)
