### ISSUE TITLE
Can you update it to 1.20.1 it would be really helpful!

### ISSUE THREAD

**Issue by Python9874** [Zgoly/Meteorist#29]
### Description

Everyone wants meteor client addons to support 1.20.1. Would you mind updating it to 1.20.1 the jar file so if i'm on Meteor version 1.20.1 it is compatible with fabric. Thanks alot: Seb!

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
[Done!](https://github.com/Zgoly/Meteorist/releases/tag/v1.6)
