### ISSUE TITLE
[Suggestion] Fast Bridge

### ISSUE THREAD

**Issue by kokqi** [Zgoly/Meteorist#3]
### Description

can u make something which automatically sneak at block edge (Fast Bridge)  (eagle bridge im not sure)

### Before submitting a suggestion

- [x] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
Interesting idea! I'll see if it can be implemented and if so, I will add it!

**Comment by Zgoly** [comment]
@kokqi Do you want something like this?

![gifff](https://user-images.githubusercontent.com/46041044/194146989-7c346e26-ef7d-4e36-954e-ec67e03e7140.gif)

**Comment by kokqi** [comment]
ye

**Comment by Zgoly** [comment]
Okay! Will be added in the next update.

**Comment by kokqi** [comment]
when u release tmr?

**Comment by Zgoly** [comment]
@kokqi
