### ISSUE TITLE
[Suggestion] AutoSneak suggestion, ignore stairs, slab, carpet. snow etc

### ISSUE THREAD

**Issue by kokqi** [Zgoly/Meteorist#31]
### Description

.

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
What do you mean by "ignore"? So that player doesn't snack when he stands on certain blocks, or vice versa?

**Comment by kokqi** [comment]
ye just stop crouching when stepping on stairs edge etc

**Comment by kokqi** [comment]
and I've come across a bug where when I turn off autosneak, it acts ike safewalk

**Comment by ModxVoldHunter** [comment]
oh crap

**Comment by Zgoly** [comment]
Added in [new version](https://github.com/Zgoly/Meteorist/releases/tag/v1.9). `Safe Walk` are no more included with `Auto Sneak`. If you have other suggestions, please create a new issue!
