### ISSUE TITLE
1.20.4?

### ISSUE THREAD

**Issue by ModxVoldHunter** [Zgoly/Meteorist#32]
### Description

update to the latest. meteor is updated to that version and will have a dev build out soon

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by flaryx32** [comment]
> Will be done at the end of week 🔥

Any updates on this?

**Comment by pek111** [comment]
Is it done?😭

**Comment by pixo2000** [comment]
bro please update

**Comment by Zgoly** [comment]
https://github.com/Zgoly/Meteorist/releases/tag/v1.8
