### ISSUE TITLE
[Bug] Auto Sneak keeps SafeWalk on even when both modules are turned off

### ISSUE THREAD

**Issue by ModxVoldHunter** [Zgoly/Meteorist#35]
### Describe the bug

if you have built the latest version then you'll see the bug after turning auto sneak on and off

### Steps to reproduce

```bash
build the latest version using "gradlew build" in command line
after building meteorist/build/libs/ drag the newly built jar into your mods folder along side meteor client
when you launch minecraft, go to a server or singleplayer
open the gui and turn on and then off autosneak and go on a block and try to walk off it.
```

### Meteorist Version

latest 1.8/1.20.4

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
This is weird. I just tested and everything was fine for me. Can you send video/gif of what it looks like? Then maybe I can figure out what's wrong

**Comment by ModxVoldHunter** [comment]
> This is weird. I just tested and everything was fine for me. Can you send video/gif of what it looks like? Then maybe I can figure out what's wrong

Yeah I can try, my computer can't record Minecraft that well but I'll try.

**Comment by ModxVoldHunter** [comment]
I think I know the problem now so when I built the jar. It changed stuff inside the files to fix it and created a bug which is rare.

**Comment by Zgoly** [comment]
In the [new version](https://github.com/Zgoly/Meteorist/releases/tag/v1.9), `Auto Sneak` no longer includes `Safe Walk`. For replacement, you can use `Player Pos Prediction` setting. Also, no one is stopping you from turning on `Safe Walk` while still using `Auto Sneak` (I don't think this is a cool idea).

As for the bug - it really exists, but during repeated tests it occurred to me quite rarely. Therefore, I decided to disconnect `Safe Walk` and `Auto Sneak`.
