### ISSUE TITLE
[Suggestion] Auction Scanner

### ISSUE THREAD

**Issue by snnwer** [Zgoly/Meteorist#37]
### Description

make a module that checks the lore for a user-given value (ex. 10$), the slots to check for and the refresh slot given by the player (like slot click)

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
I think with the new `Slot Click` in [new version](https://github.com/Zgoly/Meteorist/releases/tag/v1.9) you can check for lore text easily. If this is not what you wanted, please create a new issue with a more detailed suggestion.
