### ISSUE TITLE
slot clicker freezing the client

### ISSUE THREAD

**Issue by Hiradpi** [Zgoly/Meteorist#38]
### Describe the bug

I used to use slot clicker back in the 1.20.1 version it worked like a charm and made auto clickers useless but I have updated to the latest build in 1.20.4 and it just crashes 
it starts clicking but when inventory closes it freezes the whole client and Im not sure why there is no useful logs related to the issue and no useful console outputs that is why I did not attach any 
sometimes iIl get unfreezed if the server kicks me for timeout or sending too many packets if i set the delay to 1 
the settings does not matter no matter the click method (action mode) is it has the same result 
I know 1.20.4 has been a pain in the ahh for most meteor addon devs I have had several problems with my addons after switch i had to build an old commit of meteor client in order to make meteor+ work but I tested it with the latest build and i had the same issue I can send a video if its necessary

### Steps to reproduce

```bash
when the slotclicker starts clicking but when inventory closes it freezes the whole client
```

### Meteorist Version

meteor-client-0.5.6 , meteorist-1.8 

### Minecraft Version

minecraft 1.20.4 , fabric 0.15.11 , fabric-api-0.97.0 , meteor-client-0.5.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Zgoly** [comment]
Got it. This was expected, because in the new version I use timers and a while loop instead of the usual ticks. This will be fixed, and perhaps this module will be removed, replaced with a more convenient solution

**Comment by Hiradpi** [comment]
Thanks , but please don't remove this mod it has been the most useful one 
thanks for your time <3

**Comment by Zgoly** [comment]
Should be fixed in [new version](https://github.com/Zgoly/Meteorist/releases/tag/v1.9). If you have other problems, please create a new issue.
