### ISSUE TITLE
villager auto trade

### ISSUE THREAD

**Issue by Hiradpi** [Zgoly/Meteorist#39]
### Description

Could you please add a module that automatically trades with the villager when the trade GUI is opened?
The input can be the trade index, which starts from 0 and so on.
I play on a server where the shops are villager trades.

![image](https://github.com/Zgoly/Meteorist/assets/78161225/fa8ae7e8-a865-4bd7-a792-2ac547341ab0)

In this case, the trade index 0 is milk, and 4 is bread.
This helps with duping. What I've been doing until now was setting the Slot Clicker mod to slot 2, which is the trade output slot, and using a normal auto-clicker on the trade I wanted to automate.
I think the channel for the villager trades was MC|TrSel and for getting list of treades MC|TrList or minecraft:trader_list, and the trade is selected by sending a packet "select_trade" with the data slot: TradeIndex.

Thanks for your time! <3

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
[Here](https://github.com/Zgoly/Meteorist/releases/tag/v1.10)

**Comment by Hiradpi** [comment]
thank you <3
