### ISSUE TITLE
[Suggestion] Auto Mlg (with nothing)

### ISSUE THREAD

**Issue by kokqi** [Zgoly/Meteorist#4]
### Description

can you make a cheat which automatically crouch and jump when you almost reach the ground (it will negate fall damage)
Credit https://www.youtube.com/watch?v=XdDguC_iN7k

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by kokqi** [comment]
nvm ig, it doesn't work for multiplayer server like paper etc

**Comment by kokqi** [comment]
just ignore this

**Comment by Zgoly** [comment]
@kokqi Okay! If you have any ideas, post them here.
