### ISSUE TITLE
[Suggestion] Auto Telly Bridge

### ISSUE THREAD

**Issue by kokqi** [Zgoly/Meteorist#5]
### Description

can you make something which automatically walk, sprint, jump, aim at the correct interval like this
https://www.youtube.com/watch?v=RCxNp8qLXBc
(and you just need to spam blocks with FastUse)
 

### Before submitting a suggestion

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by kokqi** [comment]
sound impossible.. but ig u can make it as alternative scaffold but with specific rotation

**Comment by Zgoly** [comment]
Sorry, I think it's really almost impossible, at least for me. I think you can use mentioned fast use or autoclicker.

**Comment by kokqi** [comment]
oh alright
