### ISSUE TITLE
[Suggestion] Packet Fly for no cheat plus

### ISSUE THREAD

**Issue by kokqi** [Zgoly/Meteorist#6]
### Description

can you make this packet fly script to your addons? 
Script Showcase: https://forums.ccbluex.net/assets/uploads/files/1661852725742-packetfly.js 
Credit: https://forums.ccbluex.net/topic/4387/packet-fly-1-8-9-version?_=1665506014208

Cleaner format: https://pastebin.com/NK0bvAMX
Simple format: https://pastebin.com/gZuTN5mZ

- [X] This feature doesn't already exist.

- [X] This wasn't already suggested.

**Comment by Zgoly** [comment]
I'll check it later

**Comment by Worgle123** [comment]
We NEED this. It would make this the most popular thing in the world!!!! Maybe other No Cheat Plus workarounds could also be added.

**Comment by Zgoly** [comment]
Half a year was enough for me to understand that this is a bad idea. If server has `NoCheatPlus` plugin and won't let you fly, then problem is definitely with the server. I suggest suggesting it in [Meteor repository](https://github.com/MeteorDevelopment/meteor-client/issues).
